torch.autograd.backward  
功能：自动求取梯度  
* tensors:用于求导的张量，如loss  
* retain_graph:保存计算图  
* create_graph:创建导数计算图，用于高阶求导  
* grad_tensors:多梯度权重  

In [1]:
import torch
torch.manual_seed(10)

In [3]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
y.backward()
w.grad

tensor([5.])

In [7]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y0 = torch.mul(a, b)
y1 = torch.add(a, b)
loss = torch.cat([y0, y1], dim=0)
grad_tensors = torch.tensor([1., 2.])
loss.backward(gradient=grad_tensors)
w.grad

tensor([9.])

In [12]:
x = torch.tensor([3.], requires_grad=True)
y = torch.pow(x, 2)
grad_1 = torch.autograd.grad(y, x, create_graph=True)
grad_2 = torch.autograd.grad(grad_1[0], x)
grad_1, grad_2

((tensor([6.], grad_fn=<MulBackward0>),), (tensor([2.]),))

autograd小贴士：  
1. 梯度不自动清零  
2. 依赖于叶子结点的结点，requires_grad默认为True  
3. 叶子结点不可执行in-place  

In [14]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
for i in range(4):
    a = torch.add(w, x)
    b = torch.add(w, 1)
    y = torch.mul(a, b)
    y.backward()
    print(w.grad)

tensor([5.])
tensor([10.])
tensor([15.])
tensor([20.])


In [15]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
a.requires_grad,b.requires_grad,y.requires_grad

(True, True, True)

In [18]:
a = torch.ones((1,))
print(id(a))
a += torch.ones((1,))
print(id(a))

4722616832
4722616832


In [19]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
w.add_(1)
y.backward()

RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.