张量是一个多维数组，它是标量、向量、矩阵的高维拓展。

Tensor与Variable  
Variable是torch.autograd中的数据类型，主要用于封装Tensor，进行自动求导  
* data:被包装的Tensor  
* grad:data的梯度  
* grad_fn:创建Tensor的Function，是自动求导的关键  
* requires_grad:指示是否需要梯度  
* is_leaf:指示是否是叶子结点（张量）  

PyTorch0.4.0版开始，Variable并入Tensor  
* dtype:张量的数据类型，如torch.FloatTensor,torch.cuda.FloatTensor  
* shape:张量的形状，如（64，3，224，224）  
* device:张量所在设备，GPU/CPU，是加速的关键  



直接创建 
torch.tensor()  
功能：从data创建tensor  
* data:数据，可以是list，numpy  
* dtype:数据类型，默认与data的一致  
* device:所在设备，cuda/cpu  
* requires_grad:是否需要梯度  
* pin_memory:是否存于锁页内存


In [1]:
import torch
import numpy as np
torch.manual_seed(1)

In [2]:
arr = np.ones((3,3))
arr.dtype

dtype('float64')

In [4]:
t = torch.tensor(arr)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

torch.from_numpy(ndarray)  
功能：从numpy创建tensor  
注意事项：从torch.from_numpy创建的tensor于原ndarray共享内存，当修改其中一个的数据，另外一个也将会被改动

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
t = torch.from_numpy(arr)
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
t[0,0]=3
arr

array([[3, 2, 3],
       [4, 5, 6]])

依据数值创建  
torch.zeros()  
功能：依size创建全0张量  
* size:张量的形状，如（3,3）、（3,224,224）  
* out:输出的张量  
* layout:内存中布局形式，有strided,sparase_coo等  
* device:所在设备，gpu/cpu  
* requires_grad:是否需要梯度  

In [11]:
out_t = torch.tensor([1])
t = torch.zeros((3, 3), out=out_t)
t, out_t

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]))

torch.zeros_like()  
功能:依input形状创建全0张量  
* input:创建与input同形状的全0张量  
* dtype:数据类型  
* layout:内存中布局形式

In [18]:
a = torch.tensor([2,2])
t = torch.zeros_like(a)
t

tensor([0, 0])

torch.ones()  
torch.ones_like()  
功能：依input形状创建全1张量  
* size:张量的形状，如（3,3）、（3,224,224）  
* detype:数据类型
* layout:内存中布局形式，有strided,sparase_coo等  
* device:所在设备，gpu/cpu  
* requires_grad:是否需要梯度  

torch.full()  
torch.full_like()  
功能：依input形状创建全0张量  
* size:张量的形状，如(3, 3)  
* fill_value:张量的值  


In [12]:
t = torch.full((3,3),10)
t

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

torch.arange()  
功能：创建等差的1维张量  
注意事项：数值区间为[start, end)  
* start:数列起始值  
* end:数列结束值  
* step:数列公差，默认为1  

In [15]:
t = torch.arange(2,10,2)
t

tensor([2, 4, 6, 8])

torch.linspace()  
功能：创建均分的1维张量  
注意事项：数值区间维[start, end]  
* start:数列起始值  
* end:数列结束值  
* steps:数列长度  

步长=（end-start)/(steps-1)

In [19]:
t = torch.linspace(2,10,4)
t

tensor([ 2.0000,  4.6667,  7.3333, 10.0000])

torch.logspace()  
功能：创建对数均分的1维张量  
注意事项：长度为steps，底为base  
* start:数列起始值  
* end:数列结束值  
* steps:数列长度  
* base:对数函数的底，默认为10  

In [23]:
t = torch.logspace(2,10,5)
t

tensor([1.0000e+02, 1.0000e+04, 1.0000e+06, 1.0000e+08, 1.0000e+10])

torch.eye()  
功能：创建单位对角矩阵（2维张量）  
注意事项：默认为方阵  
* n:矩阵行数  
* m:矩阵列数  


In [25]:
t = torch.eye(2,3)
t

tensor([[1., 0., 0.],
        [0., 1., 0.]])

依概率分布创建张量  
torch.normal()  
功能：生成正态分布（高斯分布）  
* mean:均值  
* std:标准差


In [27]:
t = torch.normal(0.0, 1.0, (3,3))
t

tensor([[-0.5631, -0.8923, -0.0583],
        [-0.1955, -0.9656,  0.4224],
        [ 0.2673, -0.4212, -0.5107]])

In [29]:
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
#必须设置dtype否则会报错
t = torch.normal(mean, std)
t

tensor([-0.5727,  1.7535, 13.7610, -3.3252])

torch.randn()  
torch.randn_like()  
功能：生成标准正态分布  
* size:张量的形状

In [31]:
t = torch.randn((3,3))
t

tensor([[ 1.5987, -1.2770,  0.3255],
        [-0.4791,  1.3790,  2.5286],
        [ 0.4107, -0.9880, -0.9081]])

In [34]:
a = torch.tensor([1.0, 2.0, 3.0])
#数据类型必须为torch.float
t = torch.randn_like(a)
t

tensor([ 0.5423,  0.1103, -2.2590])

torch.rand()  
torch.rand_like()  
功能：在区间[0,1)上，生成均匀分布  
torch.randint()  
torch.randint_like()  
功能：在区间[low, high)生成整数均匀分布
* size:张量的形状  


In [35]:
t = torch.rand((3,3))
t

tensor([[0.1205, 0.1452, 0.7720],
        [0.3828, 0.7442, 0.5285],
        [0.6642, 0.6099, 0.6818]])

In [37]:
t = torch.randint(1,10,(3,3))
t

tensor([[8, 5, 8],
        [7, 6, 5],
        [2, 7, 1]])

torch.randperm()  
功能：生成从0到n-1的随机排列  
* n:张量的长度  

In [38]:
t = torch.randperm(5)
t

tensor([2, 4, 1, 3, 0])

torch.bernoulli()  
功能：以input为概率，生成伯努利分布  
* input:概率值

In [44]:
p = torch.tensor([0.3,0.2,0.4,0.8])
t = torch.bernoulli(p)
t

tensor([0., 1., 0., 0.])