张量操作

张量拼接与切分  
torch.cat()  
功能： 将张量按维度dim进行拼接  
* tensors:张量序列  
* dim:要拼接的维度  

In [1]:
import torch
torch.manual_seed(1)

In [3]:
t = torch.ones((2, 3))
t_0 = torch.cat([t, t], dim=0)
t_1 = torch.cat([t, t], dim=1)
t_0, t_1

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]))

torch.stack()  
功能：在新创建的维度dim上进行拼接  
* tensors:张量序列  
* dim:要拼接的维度

In [7]:
t = torch.ones((2, 3))
t_stack = torch.stack([t, t, t], dim=0)
t_stack, t_stack.shape

(tensor([[[1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.]]]),
 torch.Size([3, 2, 3]))

torch.chunk()  
功能：将张量按维度dim进行平均切分  
返回值：张量列表  
注意事项：若不能整除，最后一份张量小于其他张量  
* input:要切分的张量  
* chunks:要切分的份数  
* dim:要切分的维度

In [20]:
a = torch.ones((2,4,8))
t_chunk = torch.chunk(a, chunks=2, dim=1)
for idx, t in enumerate(t_chunk):
    print(t.shape)


torch.Size([2, 2, 8])
torch.Size([2, 2, 8])


torch.split()  
功能：将张量按维度dim进行切分  
返回值：张量列表  
* tensor:要切分的张量  
* split_size_or_sections:为int时，表示每一份的长度；为list时，按list元素切分  
* dim:要切分的维度

In [30]:
a = torch.ones((2, 5))
t_split = torch.split(a, [1,1,3], dim=1)
for idx, t in enumerate(t_split):
    print(t.shape)


torch.Size([2, 1])
torch.Size([2, 1])
torch.Size([2, 3])


torch.index_select()  
功能：在维度dim上，按index索引数据  
返回值：依index索引数据拼接的张量  
* input:要索引的张量  
* dim:要索引的维度  
* index:要索引数据的序号  


In [31]:
t = torch.randint(0, 9, size=(3, 3))#必须为torch.long
t_select = torch.index_select(t, dim=0, index=idx)
t,t_select

(tensor([[4, 5, 0],
         [5, 7, 1],
         [2, 5, 8]]),
 tensor([[4, 5, 0],
         [2, 5, 8]]))

torch.masked_select()  
功能：按mask中的True进行索引  
返回值：一维张量  
* input:要索引的张量  
* mask:与input同形状的布尔类型张量  


In [32]:
t = torch.randint(0, 9, size=(3, 3))
mask = t.le(5)
t_select = torch.masked_select(t,mask)
t, t_select

(tensor([[0, 2, 3],
         [1, 8, 4],
         [0, 3, 6]]),
 tensor([0, 2, 3, 1, 4, 0, 3]))

torch.reshape()
功能：变换张量形状  
注意事项：当张量在内存中是连续的，新张量与input共享数据内存  
* input:要变换的张量  
* shape:新张量的形状

In [33]:
t = torch.randperm(8)
t_reshape = torch.reshape(t, (2, 4))
t_reshape

tensor([[2, 0, 1, 6],
        [3, 4, 7, 5]])

torch.transpose()  
功能：交换张量的两个维度  
* input:要变换的张量  
* dim0:要交换的维度  
* dim1:要交换的维度  


In [34]:
t = torch.rand((2,3,4))
t_transpose = torch.transpose(t,0,1)
t_transpose.shape

torch.Size([3, 2, 4])

torch.t()  
功能：2维张量转置，对矩阵而言，等价于torch.transpose(input,0,1)

In [35]:
t = torch.rand((2,3))
tt = torch.t(t)
tt.shape

torch.Size([3, 2])

torch.squeeze()  
功能：压缩长度为1的维度(轴)  
* dim:若为None，移除所有长度为1的轴；若指定维度，当且仅当该轴长度为1时，可以被移除；

In [36]:
t = torch.rand((1,2,3,1))
t_squeeze = torch.squeeze(t)
t_squeeze.shape

torch.Size([2, 3])

torch.unsqueeze()  
功能：依据dim扩展维度  
* dim:扩展的维度  

In [37]:
t = torch.rand((1,2,3))
t_unsqueeze = torch.unsqueeze(t,0)
t_unsqueeze.shape

torch.Size([1, 1, 2, 3])

张量数学运算  
加减乘除  
对数，指数，幂函数  
三角函数  
torch.add()  
功能：逐元素计算input+alpha*other  
* input:第一个张量  
* alpha:乘项因子  
* other:第二个张量  


In [38]:
t_0 = torch.randn((3,3))
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0, 10, t_1)
t_0, t_1, t_add

(tensor([[-0.5124, -0.2997,  0.6655],
         [ 0.2734,  2.0731, -1.9578],
         [ 2.8238,  0.2384, -0.6317]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 9.4876,  9.7003, 10.6655],
         [10.2734, 12.0731,  8.0422],
         [12.8238, 10.2384,  9.3683]]))